### ISSUE TITLE
 Installation problem

### ISSUE THREAD

**Issue by Psula23** [weng-lab/TEMP2#14]
Hi,
I would like to use your tool, unfortunately I have some problems. 
When I run the program on test data, I see the following problems: 

```
/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/TEMP2 insertion -l test.1.fastq.gz -r test.2.fastq.gz -I bwa_index/chr2L -g chr2L.fa -R transposon.fa -t rmsk.bed -o test_output -c 2

Testing required softwares:
bwa: /home/pgr/miniconda3/envs/temp22/bin/bwa
samtools: /home/pgr/miniconda3/envs/temp22/bin/samtools
bedtools: /home/pgr/miniconda3/envs/temp22/bin/bedtools
------ Start pipeline ------
bam file not specified, map raw reads tp genome via bwa mem	nie, 16 kwi 2023, 12:53:27 CEST
transform sam to sorted bam and index it	nie, 16 kwi 2023, 12:53:35 CEST
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
get concordant-uniq-split reads	nie, 16 kwi 2023, 12:53:40 CEST
awk: line 2: function and never defined
awk: line 2: function and never defined
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 0 reads
check fragment length	nie, 16 kwi 2023, 12:53:41 CEST
awk: line 2: function and never defined
Błąd w poleceniu 'read.table(Args[6], header = F, row.names = NULL)':
  nie ma dostępnych linii na wejściu
Wykonywanie wstrzymane
insert size set to 95 quantile: 
/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/TEMP2_insertion.sh: wiersz 172: [: -gt: oczekiwano operatora jednoargumentowego
get mate seq of the uniq-unpaired	nie, 16 kwi 2023, 12:53:41 CEST
awk: line 2: function and never defined
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 0 reads
map paired split uniqMappers and unpaired uniqMappers to transposons	nie, 16 kwi 2023, 12:53:41 CEST
merge fragments in genome and transposon	nie, 16 kwi 2023, 12:53:41 CEST
awk: line 40: function and never defined
awk: line 40: function and never defined
awk: line 78: function and never defined
awk: line 78: function and never defined
awk: line 78: function and never defined
test.t is empty
merge support reads in the same direction within - 	nie, 16 kwi 2023, 12:53:42 CEST
mkdir: nie można utworzyć katalogu „test.supportReads”: Plik istnieje
/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/TEMP2_insertion.sh: wiersz 208: [: -: oczekiwano wyrażenia całkowitego

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
Traceback (most recent call last):
  File "/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/processMergedBed.py", line 10, in main
    tel = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'test.supportReads/*.merged.merged.bed'
Traceback (most recent call last):
  File "/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/processMergedBed.py", line 10, in main
    tel = int(sys.argv[2])
IndexError: list index out of range
Traceback (most recent call last):
  File "/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/processMergedBed.py", line 10, in main
    tel = int(sys.argv[2])
IndexError: list index out of range
merge support reads in different direction within 2 X - 	nie, 16 kwi 2023, 12:53:42 CEST
/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/mergeProcessedBed.sh in.processed.bed insert_size read_length out.prefix
/mnt/655a20f4-6ab2-4a63-84cc-be645d22970d/temp22/TEMP2/bin/mergeProcessedBed.sh in.processed.bed insert_size read_length out.prefix
filter candidate insertions which overlap with the same transposon insertion or in high depth region	nie, 16 kwi 2023, 12:53:42 CEST
filter candidate insertions in high depth region	nie, 16 kwi 2023, 12:53:42 CEST
average read number for 200bp bins is 0, set read number cutoff to 0
Filtered insertion number: 0 - 0 (overlap rmsk) 0 (short insertion) - 0 (high depth) = 0
generate the overall distribution of transposon mapping reads, first map all reads to transposon	nie, 16 kwi 2023, 12:53:48 CEST
sam to bed and bedGraph, multiple mappers are divided by their map times	nie, 16 kwi 2023, 12:53:54 CEST
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
mkdir: nie można utworzyć katalogu „test.transposonMapping”: Plik istnieje
estimate de novo insertion number for each transposon using singleton reads	nie, 16 kwi 2023, 12:53:58 CEST
Error: unable to open file or unable to determine types for file test.TPregion.bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the 
  expected columns (e.g., cols 2 and 3 for BED).
Error: unable to open file or unable to determine types for file test.TPregion.bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the 
  expected columns (e.g., cols 2 and 3 for BED).
Błąd w poleceniu '`[.data.frame`(soma, , 4)':nie wybrano kolumn
Wywołania: [ -> [.data.frame
Wykonywanie wstrzymane
generate distribution figures for singleton supporting reads	nie, 16 kwi 2023, 12:53:58 CEST
Błąd w poleceniu 'read.table(Args[6], header = F, row.names = NULL)':
  nie ma dostępnych linii na wejściu
Wykonywanie wstrzymane
filter unreliable singleton insertions, also filter 2p insertions overlapped with similar reference transposon copies	nie, 16 kwi 2023, 12:53:59 CEST
Error: unable to open file or unable to determine types for file test.tmp

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the 
  expected columns (e.g., cols 2 and 3 for BED).
Error: unable to open file or unable to determine types for file test.tmp

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the 
  expected columns (e.g., cols 2 and 3 for BED).
Calculate frequency of each transposon insertion	nie, 16 kwi 2023, 12:53:59 CEST
[main_samview] region "chr2L:0-0" could not be parsed. Continue anyway.
Error: unable to open file or unable to determine types for file test.tmp

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the 
  expected columns (e.g., cols 2 and 3 for BED).
get TSD, remove redundant insertions and recalculate de novo insertion rate	nie, 16 kwi 2023, 12:53:59 CEST
awk: line 6: regular expression compile failed (missing operand)
|

*****
***** ERROR: Requested column 2, but database file - only has fields 1 - 0.
Error: unable to open file or unable to determine types for file test.TPregion.bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the 
  expected columns (e.g., cols 2 and 3 for BED).
Expecting number field 3 line 2 of test.t, got ;;
calculate de novo insertion rate per genome	nie, 16 kwi 2023, 12:53:59 CEST
clean tmp files	nie, 16 kwi 2023, 12:53:59 CEST
Done, Congras!!!🍺🍺🍺


```
I have the environment installed in miniconda with:

```
perl                      5.32.1          2_h7f98852_perl5    conda-forge
perl-algorithm-diff       1.1903          pl5321hdfd78af_3    bioconda
perl-base                 2.23            pl5321hdfd78af_2    bioconda
perl-bio-asn1-entrezgene  1.73            pl5321hdfd78af_3    bioconda
perl-bio-coordinate       1.007001        pl5321hdfd78af_3    bioconda
perl-bio-featureio        1.6.905         pl5321hdfd78af_4    bioconda
perl-bio-samtools         1.43            pl5321h7132678_3    bioconda
perl-bio-searchio-hmmer   1.7.3           pl5321hdfd78af_0    bioconda
perl-bio-tools-phylo-paml 1.7.3           pl5321hdfd78af_3    bioconda
perl-bio-tools-run-alignment-clustalw 1.7.4           pl5321hdfd78af_3    bioconda
perl-bio-tools-run-alignment-tcoffee 1.7.4           pl5321hdfd78af_4    bioconda
perl-bioperl              1.7.8                hdfd78af_1    bioconda
perl-bioperl-core         1.7.8           pl5321hdfd78af_1    bioconda
perl-bioperl-run          1.007003        pl5321hdfd78af_0    bioconda
perl-business-isbn        3.007           pl5321hdfd78af_0    bioconda
perl-business-isbn-data   20210112.006    pl5321hdfd78af_0    bioconda
perl-capture-tiny         0.48            pl5321hdfd78af_2    bioconda
perl-carp                 1.38            pl5321hdfd78af_4    bioconda
perl-class-data-inheritable 0.09            pl5321hdfd78af_0    bioconda
perl-compress-raw-zlib    2.105           pl5321h87f3376_0    bioconda
perl-constant             1.33            pl5321hdfd78af_2    bioconda
perl-data-dumper          2.183           pl5321hec16e2b_1    bioconda
perl-db_file              1.858           pl5321h166bdaf_0    conda-forge
perl-devel-stacktrace     2.04            pl5321hdfd78af_1    bioconda
perl-digest-hmac          1.04            pl5321hdfd78af_0    bioconda
perl-digest-md5           2.58            pl5321hec16e2b_1    bioconda
perl-encode               3.19            pl5321hec16e2b_1    bioconda
perl-encode-locale        1.05            pl5321hdfd78af_7    bioconda
perl-exception-class      1.45            pl5321hdfd78af_0    bioconda
perl-exporter             5.72            pl5321hdfd78af_2    bioconda
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-file-listing         6.15            pl5321hdfd78af_0    bioconda
perl-file-slurp-tiny      0.004           pl5321hdfd78af_2    bioconda
perl-file-sort            1.01            pl5321hdfd78af_3    bioconda
perl-file-spec            3.48_01         pl5321hdfd78af_2    bioconda
perl-getopt-long          2.54            pl5321hdfd78af_0    bioconda
perl-html-parser          3.81            pl5321h9f5acd7_0    bioconda
perl-html-tagset          3.20            pl5321hdfd78af_4    bioconda
perl-http-cookies         6.10            pl5321hdfd78af_0    bioconda
perl-http-daemon          6.16            pl5321hdfd78af_0    bioconda
perl-http-date            6.05            pl5321hdfd78af_0    bioconda
perl-http-message         6.36            pl5321hdfd78af_0    bioconda
perl-http-negotiate       6.01            pl5321hdfd78af_4    bioconda
perl-io-html              1.004           pl5321hdfd78af_0    bioconda
perl-io-socket-ssl        2.074           pl5321hdfd78af_0    bioconda
perl-io-string            1.08            pl5321hdfd78af_4    bioconda
perl-io-tty               1.16            pl5321hec16e2b_1    bioconda
perl-ipc-run              20200505.0      pl5321hdfd78af_0    bioconda
perl-libwww-perl          6.67            pl5321hdfd78af_0    bioconda
perl-libxml-perl          0.08            pl5321hdfd78af_3    bioconda
perl-lwp-mediatypes       6.04            pl5321hdfd78af_1    bioconda
perl-mime-base64          3.16            pl5321hec16e2b_2    bioconda
perl-net-http             6.22            pl5321hdfd78af_0    bioconda
perl-net-ssleay           1.92            pl5321h0e0aaa8_1    bioconda
perl-ntlm                 1.09            pl5321hdfd78af_5    bioconda
perl-parent               0.236           pl5321hdfd78af_2    bioconda
perl-socket               2.027           pl5321hec16e2b_3    bioconda
perl-sub-uplevel          0.2800          pl5321hec16e2b_4    bioconda
perl-test-deep            1.130           pl5321hdfd78af_0    bioconda
perl-test-differences     0.69            pl5321hdfd78af_0    bioconda
perl-test-exception       0.43            pl5321hdfd78af_3    bioconda
perl-test-most            0.38            pl5321hdfd78af_0    bioconda
perl-test-warn            0.36            pl5321hdfd78af_2    bioconda
perl-text-diff            1.45            pl5321hdfd78af_1    bioconda
perl-time-local           1.30            pl5321hdfd78af_0    bioconda
perl-timedate             2.33            pl5321hdfd78af_2    bioconda
perl-tree-dag_node        1.32            pl5321hdfd78af_0    bioconda
perl-try-tiny             0.31            pl5321hdfd78af_1    bioconda
perl-uri                  5.12            pl5321hdfd78af_0    bioconda
perl-url-encode           0.03            pl5321h9ee0642_0    bioconda
perl-www-robotrules       6.02            pl5321hdfd78af_4    bioconda
perl-xml-dom              1.46            pl5321hdfd78af_1    bioconda
perl-xml-dom-xpath        0.14            pl5321hdfd78af_2    bioconda
perl-xml-parser           2.44_01         pl5321hc3e0081_1003    conda-forge
perl-xml-regexp           0.04            pl5321hdfd78af_3    bioconda
perl-xml-xpathengine      0.14            pl5321hdfd78af_3    bioconda
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
python                    2.7.18               h42bf7aa_3  
python_abi                2.7                    1_cp27mu    conda-forge
r                         4.2             r42hd8ed1ab_1006    conda-forge
r-base                    4.2.0                h1ae530e_0  
r-boot                    1.3_28.1          r42hc72bb7e_0    conda-forge
r-class                   7.3_21            r42h133d619_0    conda-forge
r-cluster                 2.1.4             r42h8da6f51_0    conda-forge
r-codetools               0.2_19            r42hc72bb7e_0    conda-forge
r-foreign                 0.8_84            r42h133d619_0    conda-forge
r-kernsmooth              2.23_20           r42hd009a43_1    conda-forge
r-lattice                 0.21_8            r42h133d619_0    conda-forge
r-mass                    7.3_58.3          r42h133d619_0    conda-forge
r-matrix                  1.5_4             r42he1ae0d6_0    conda-forge
r-mgcv                    1.8_42            r42he1ae0d6_0    conda-forge
r-nlme                    3.1_157           r42h640688f_0  
r-nnet                    7.3_18            r42h06615bd_1    conda-forge
r-recommended             4.2             r42hd8ed1ab_1005    conda-forge
r-rpart                   4.1.19            r42h06615bd_0    conda-forge
r-spatial                 7.3_16            r42h133d619_0    conda-forge
r-survival 
```

Same errors for Python version 3.8 and 2.7.

I hope you can help me get this problem solved. Sorry that some messages are in Polish, but I think the most important message is in English.
Best,
Paulina

**Comment by tianxiongbb** [comment]
Hi Paulina,

The issue is coming from a different version of “awk” you are using. I have now specified using “gawk” in TEMP2 instead of default “awk” version install in your machine. Please let me know if this works.

Best,
Tianxiong

**Comment by tianxiongbb** [comment]
Forget to mention that you need to pull the code from Github again.

Best,
Tianxiong

**Comment by Psula23** [comment]
Thank you for your answer. It turned out to be helpful and meaningful to my errors. In addition, I had to install Python version 2.7 and Bedtools outside of Miniconda (error: unrecognized command: intersectBed). And now everything works fine.

Best,
Paulina
