### ISSUE TITLE
erro on test 

### ISSUE THREAD

**Issue by unavailable-2374** [weng-lab/TEMP2#8]
I try to run the insertion test and I get this erro

"""
/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/TEMP2_insertion.sh: 第 206 行:[: -: 期待整数表达式
sort: cannot read: test.supportReads/*.bed: 没有那个文件或目录

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
Traceback (most recent call last):
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 10, in main
    tel = int(sys.argv[2])
IndexError: list index out of range
merge support reads in different direction within 2 X - 	2022年 06月 13日 星期一 09:45:06 CST
cat: test.supportReads/*.final.bed: 没有那个文件或目录
"""

this is my command 
"TEMP2 insertion -l test.1.fastq.gz -r test.2.fastq.gz -I bwa_index/chr2L -g chr2L.fa -R transposon.fa -t rmsk.bed -o test_output -c 2"

the test.insertion.bed only have the head line but without any data .

**Comment by unavailable-2374** [comment]
Attachment:
[caoshuo@login1 tmpTEMP2]$ ls test.supportReads/
*.merged.bed  *.processed.bed

thanks!!!

**Comment by tianxiongbb** [comment]
Can you upload the entire log file? Thanks!

**Comment by zhouyflab** [comment]
here is my log file 

[err.log](https://github.com/weng-lab/TEMP2/files/8900024/err.log)
[out.log](https://github.com/weng-lab/TEMP2/files/8900040/out.log)

thanks!
shuo cao

**Comment by tianxiongbb** [comment]
It looks like you don't have [R](https://www.r-project.org/) installed in your machine.

**Comment by zhouyflab** [comment]
thanks! I thought R was just for drawing.

I have successfully installed R-base, but there still have some errors 

"""
*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/TEMP2_insertion.sh:行207: ${i/.bed/.merged.bed}: 模糊的重定向

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/TEMP2_insertion.sh:行210: ${i/merged.bed/processed.bed}: 模糊的重定向
Traceback (most recent call last):
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 10, in main
    tel = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'test.supportReads/*.merged.merged.merged.bed'
Traceback (most recent call last):
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 11, in main
    ins = int(sys.argv[3])
IndexError: list index out of range
Traceback (most recent call last):
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 11, in main
    ins = int(sys.argv[3])
IndexError: list index out of range
/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/TEMP2_insertion.sh:行210: ${i/merged.bed/processed.bed}: 模糊的重定向
Traceback (most recent call last):
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 11, in main
    ins = int(sys.argv[3])
IndexError: list index out of range
Traceback (most recent call last):
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 108, in <module>
    main()
  File "/public/agis/zhouyongfeng_group/caoshuo/tools/TEMP2/bin/processMergedBed.py", line 11, in main
    ins = int(sys.argv[3])
IndexError: list index out of range
"""
and there is the output file

![image](https://user-images.githubusercontent.com/103104171/173716896-6ab29abc-b88a-4ac1-b5eb-4a1c90fb9595.png)

thanks for your reply!!! wish you have a good day~

cao

**Comment by tianxiongbb** [comment]
Hi cao, sorry for the late reply. I hope you have solved the issue. If not, it is probably due to the version of samtools, you might want to try install samtools with version ≥ 1.9 to see if it works. I will close thread.
